name: Hadolint Testing
on:
  pull_request:
    types: [synchronize, opened, reopened]
jobs:
  hadolint-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true
