name: main

on: pull_request

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker
        run: |
          cd infrastructure
          make build
          make up
          docker-compose exec -T app composer create-project --prefer-dist laravel/laravel .
          docker-compose exec -T app composer require predis/predis
          docker-compose exec -T app composer require doctrine/dbal
          docker-compose exec -T app php artisan --version
